// node/benchmarks/curated/fixtures/Orders.tsx
import type { ReactElement } from "react";
import { useMemo, useState } from "react";

interface Order {
  id: string;
  customer: string;
  total: number;
  paid: boolean;
}
interface Props {
  orders: readonly Order[];
  onSelect: (id: string) => void;
}

// Searchable, typed JSX with expressions and event handlers.
export function OrderTable({ orders, onSelect }: Props): ReactElement {
  const [query, setQuery] = useState("");
  const visible = useMemo(
    () => orders.filter((order) => order.customer.toLowerCase().includes(query.toLowerCase())),
    [orders, query],
  );
  const total = visible.reduce((sum, order) => sum + order.total, 0);
  return (
    <section aria-label="Orders & customers" className="orders">
      <label htmlFor="search">Search München & café</label>
      <input id="search" value={query} onChange={(event) => setQuery(event.target.value)} />
      <table>
        <thead>
          <tr>
            <th>Customer</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          {visible.map(({ id, customer, total, paid }) => (
            <tr key={id} data-paid={paid} onClick={() => onSelect(id)}>
              <td>{customer}</td>
              <td>
                {total.toFixed(2)} {paid ? <strong>Paid</strong> : <em>Pending</em>}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      {/* A literal and a JSX interpolation share the same line. */}
      <footer>
        {visible.length} orders · €{total.toFixed(2)}
      </footer>
    </section>
  );
}

// node/benchmarks/curated/fixtures/Orders.vue
<script setup lang="ts">
import { computed, ref } from "vue";
interface Order {
  id: string;
  customer: string;
  total: number;
  paid: boolean;
}
const props = defineProps<{ orders: Order[] }>();
const emit = defineEmits<{ select: [id: string] }>();
const query = ref("");
const visible = computed(() =>
  props.orders.filter((order) => order.customer.includes(query.value)),
);
const total = computed(() => visible.value.reduce((sum, order) => sum + order.total, 0));
</script>

<template>
  <!-- TypeScript, Vue directives and an embedded SCSS style block. -->
  <section class="orders">
    <h1>München &amp; café</h1>
    <input v-model="query" aria-label="Search customers" />
    <ul v-if="visible.length">
      <li
        v-for="order in visible"
        :key="order.id"
        :class="{ paid: order.paid }"
        @click="emit('select', order.id)"
      >
        <strong>{{ order.customer }}</strong
        ><span>€{{ order.total.toFixed(2) }}</span>
      </li>
    </ul>
    <p v-else>No orders matching &lt;{{ query }}&gt;.</p>
    <output>€{{ total.toFixed(2) }}</output>
  </section>
</template>

<style scoped lang="scss">
$accent: #2563eb;
.orders {
  display: grid;
  gap: 1rem;
  .paid {
    color: $accent;
    &:hover {
      text-decoration: underline;
    }
  }
}
</style>
